
/*
* first version
*/
<?php

        // ✅ AGREGADO: armar video con SKU e inyectarlo al JSON
    $sku = $block->getProduct()->getSku();
    $videoUrl = "https://www.vid.com/" . $sku . "?url=1";

    $videoItem = [
        'isVideo' => true,
        'type' => 'video',
        'videoUrl' => $videoUrl,
        'thumb' => $videoUrl, // cambiar si tenés thumbnail distinta
        'img' => $videoUrl
    ];

    // Tomar JSON original
    $galleryJson = $block->getGalleryImagesJson();
    $galleryArray = json_decode($galleryJson, true);

    // Agregar video
    $galleryArray[] = $videoItem;

    // Volver a JSON
    $newGalleryJson = json_encode($galleryArray);

?>
......
.......
<!-- to change >
                "data": <?= /* @noEscape */ $newGalleryJson ?>,








/*
*  second version 
*/



<?php
    // ✅ AGREGADO: armar video con URL fija de Vimeo
    $videoUrl = "https://player.vimeo.com/video/76979871";
    $thumbUrl = "https://i.vimeocdn.com/video/452001751_640.jpg"; // thumbnail del video

    $videoItem = [
        'isVideo' => true,
        'type' => 'video',
        'videoUrl' => $videoUrl,
        'thumb' => $thumbUrl,
        'html' => '<iframe src="' . $videoUrl . '" width="640" height="360" frameborder="0" allowfullscreen></iframe>'
    ];

    // Tomar JSON original
    $galleryJson = $block->getGalleryImagesJson();
    $galleryArray = json_decode($galleryJson, true);

/*
*  api to get info vimeo 
*/


https://vimeo.com/api/v2/video/1132940125.json
